### PR TITLE
Prodigy

### PR DESCRIPTION
**Pull request by rejeep**
Note that I added version `0.1` to the package. I don't know what the version is? Please change it if it's wrong. I also added Cask because discover depends on makey.

### CODE REVIEW

**Comment by mickeynp** [comment]
Hi rejeep,

Thanks for the PR, but there are a couple of issues.

I'm not sure putting custom package initialization code in discover.el is the right way around. As per my updated README -- and apologies for not having that ready immediately, this was supposed to be a quick prototype but it proved more popular than I initially thought it would -- I included a snippet of code for detecting discover.el and injecting itself into it. I now realise that this is perhaps not clear enough - I will fix the documentation and add better end points. Apologies for that.

Thanks for adding the version tag; all this package malarkey is impossible for me to keep track of. I'm also not sure what Cask is or what it adds that the built-in package manager doesn't already do? Pulling Discover from MELPA will also get Makey.

Thanks again for the work.

Mickey.

**Comment by mickeynp** [comment]
I have rewritten the API. Can you please try it out now? From within your own module you just need to follow the instructions in README.rst

https://github.com/mickeynp/discover.el/tree/feature/better-api

It should be much easier. Apologies for the trouble.

**Comment by rejeep** [comment]
> I'm also not sure what Cask is or what it adds that the built-in package manager doesn't already do? Pulling Discover from MELPA will also get Makey.

Cask (https://github.com/cask/cask) is a dependency manager for Emacs. If someone is to hack on discover, all they have to do now is install Cask and run `cask install` and all dependencies will be installed. If you then run `cask exec emacs ...` it will make those dependencies available in Emacs.

> I have rewritten the API. Can you please try it out now?

Sure thing, will give it a go!

**Comment by rejeep** [comment]
I tried this out a bit and it works. But for Prodigy, I would rather prefer a function `discover-show-context-menu`. That way I can bind a key myself:

``` lisp
(defun prodigy-help ()
  (interactive)
  (if (featurep 'discover)
      (discover-show-context-menu
       '(actions
         ("Navigation"
          ("n" "next service" prodigy-next)
          ("p" "prev service" prodigy-prev)
          ("M-<" "first service" prodigy-first)
          ("M->" "last service" prodigy-last))
         ...))
    (describe-mode)))

(define-key prodigy-mode-map (kbd "?") 'prodigy-help)
```

What do you think?

**Comment by rejeep** [comment]
> That way I can bind a key myself

And by that I mean that I will bind the key in `prodigy.el`.

**Comment by mickeynp** [comment]
You can show an existing context menu that has already been initialized. Makey will create it for you. It's called `makey-key-mode-popup-<foobar>`. However it is dynamically created and you cannot invoke an arbitrary context menu like your example above; there's too much magic under the hood to ever make it that simple, unfortunately, as it creates a host of commands and what-have-you.

A better alternative is to initialise it as per my README example and then in your snippet above you can tell discover to show the popup.

I've pushed some code that lets you do this. Here's an example: `(discover-show-context-menu 'prodigy)`.

(Oh, and a small warning: I renamed `discover-add-key-group` to `discover-add-context-menu` for consistency.)

**Comment by rejeep** [comment]
Ok, after some consideration I figured this was the best approach: https://github.com/rejeep/prodigy.el/tree/discover. So please merge the branch, so that I can merge mine :)

**Comment by rejeep** [comment]
Great, thanks! :)

**Comment by mickeynp** [comment]
You're welcome. Sorry it took so long to resolve this.

**Comment by rejeep** [comment]
Not at all, you've been most helpful! :)

**Pull request closed without merging**
